// components/TermsPage.jsx
export default function TermsPage({ onClose }) {
  return (
    <div style={{ position: "fixed", inset: 0, background: "#0a0a0a", zIndex: 2000, overflowY: "auto" }}>
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "40px 24px 80px" }}>
        <button type="button" onClick={onClose}
          style={{ background: "none", border: "1px solid rgba(245,240,232,0.2)", color: "#f5f0e8", padding: "8px 16px", borderRadius: 8, cursor: "pointer", marginBottom: 32, fontSize: 14 }}>
          ← Back
        </button>
        <h1 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 40, fontWeight: 900, color: "#f5f0e8", marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ color: "rgba(245,240,232,0.4)", fontSize: 13, marginBottom: 40 }}>Last updated: March 13, 2026</p>

        {[
          {
            title: "1. Acceptance of Terms",
            body: `By accessing or using Che AF ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App. Che AF is operated as a sole trader business registered in New Zealand.`
          },
          {
            title: "2. Description of Service",
            body: `Che AF is an AI-powered recipe and meal planning application. We offer a free tier with limited AI calls per month and a Pro subscription ($2.99 NZD/month) with unlimited access to all features including AI recipe generation, fridge scanning, meal planning, and cloud sync.`
          },
          {
            title: "3. Pioneer Member Offer",
            body: `The first 200 users to register ("Pioneer Members") receive Pro access free for life, subject to the offer expiring on April 13, 2026, or when 200 Pioneer spots are filled — whichever comes first. This offer is non-transferable and applies to the registered account only. Che AF reserves the right to modify or discontinue this offer with reasonable notice.`
          },
          {
            title: "4. User Accounts",
            body: `You must provide a valid email address to create an account. You are responsible for maintaining the confidentiality of your password. You agree to notify us immediately of any unauthorised use of your account. We reserve the right to terminate accounts that violate these terms.`
          },
          {
            title: "5. Subscriptions & Payments",
            body: `Pro subscriptions are billed monthly at $2.99 NZD via Stripe. You may cancel at any time through your account settings. Cancellation takes effect at the end of the current billing period. We do not offer refunds for partial months. Prices may change with 30 days notice.`
          },
          {
            title: "6. AI-Generated Content",
            body: `Recipes and content generated by AI are provided for informational purposes only. Che AF does not guarantee the accuracy, safety, or suitability of AI-generated recipes. Always use your judgment when preparing food, particularly regarding allergies, dietary restrictions, and food safety.`
          },
          {
            title: "7. User Content",
            body: `You retain ownership of any recipes, photos, or content you upload to the App. By uploading content, you grant Che AF a non-exclusive licence to store and display that content within the App for the purpose of providing the service.`
          },
          {
            title: "8. Acceptable Use",
            body: `You agree not to misuse the App, attempt to reverse engineer it, use it for commercial scraping, or violate any applicable laws. We reserve the right to suspend or terminate access for violations.`
          },
          {
            title: "9. Limitation of Liability",
            body: `Che AF is provided "as is" without warranties of any kind. To the fullest extent permitted by NZ law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the App.`
          },
          {
            title: "10. Changes to Terms",
            body: `We may update these terms from time to time. Continued use of the App after changes constitutes acceptance of the new terms. We will notify users of significant changes via email.`
          },
          {
            title: "11. Contact",
            body: `For any questions about these Terms, contact us at support@che-af.vercel.app`
          },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: 32 }}>
            <h2 style={{ fontFamily: "'Playfair Display', Georgia, serif", fontSize: 20, fontWeight: 700, color: "#f5f0e8", marginBottom: 10 }}>{section.title}</h2>
            <p style={{ fontFamily: "'DM Sans', system-ui, sans-serif", fontSize: 15, color: "rgba(245,240,232,0.6)", lineHeight: 1.8 }}>{section.body}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
